const DB='controles-sisplan-db', VER=2, R='reports', H='hours', S='settings';
const CLIENTS=(window.SISPLAN_CLIENTES||[]).map(c=>Array.isArray(c)?{codigo:c[0],fantasia:c[1],cidade:c[2],uf:c[3],nome:c[4]}:c);
let reports=[], hours=[], selected=null, asc=true;
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), fh=v=>`${Number(v||0).toLocaleString('pt-BR',{maximumFractionDigits:2})} h`;
function db(){return new Promise((res,rej)=>{let x=indexedDB.open(DB,VER);x.onupgradeneeded=e=>{let d=e.target.result;[R,H,S].forEach(n=>{if(!d.objectStoreNames.contains(n))d.createObjectStore(n,{keyPath:n===S?'key':'id'})})};x.onsuccess=()=>res(x.result);x.onerror=()=>rej(x.error)})}
async function all(st){let d=await db();return new Promise((res,rej)=>{let x=d.transaction(st,'readonly').objectStore(st).getAll();x.onsuccess=()=>res(x.result);x.onerror=()=>rej(x.error)})}
async function put(st,o){let d=await db();return new Promise((res,rej)=>{let t=d.transaction(st,'readwrite');t.objectStore(st).put(o);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function del(st,id){let d=await db();return new Promise((res,rej)=>{let t=d.transaction(st,'readwrite');t.objectStore(st).delete(id);t.oncomplete=res;t.onerror=()=>rej(t.error)})}
async function getSet(k,f=''){let a=await all(S),x=a.find(i=>i.key===k);return x?.value??f}
const setSet=(k,v)=>put(S,{key:k,value:v});
const byCode=c=>CLIENTS.find(x=>String(x.codigo)===String(c));
const total=e=>Number(e.hours||0)*(Number(e.hourRate||0)+(e.travel?Number(e.travelRate||0):0));
const dateBR=s=>{if(!s)return'';let [y,m,d]=s.split('-');return`${d}/${m}/${y}`};
const toText=f=>new Promise((r,j)=>{let x=new FileReader();x.onload=()=>r(x.result);x.onerror=()=>j(x.error);x.readAsText(f)});
const toData=f=>new Promise((r,j)=>{let x=new FileReader();x.onload=()=>r(x.result);x.onerror=()=>j(x.error);x.readAsDataURL(f)});
function dl(txt,n,type='text/plain'){let u=URL.createObjectURL(new Blob([txt],{type})),a=document.createElement('a');a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
async function seed(){reports=await all(R);if(!reports.some(x=>x.id==='ficha-tecnica-inicial'))await put(R,{id:'ficha-tecnica-inicial',screenName:'APP - FICHA TÉCNICA',formName:'FichaTecnica',category:'Relatórios / Telas',tags:['ficha técnica','produto','app'],notes:'Relatório inicial cadastrado a partir do arquivo FichaTecnica.fr3.',favorite:true,builtIn:true,fr3Url:'assets/FichaTecnica.fr3',fr3Name:'FichaTecnica.fr3',createdAt:new Date().toISOString()})}
function renderReports(){let term=q('#globalSearch').value.toLowerCase();let list=reports.filter(r=>[r.screenName,r.formName,r.notes,(r.tags||[]).join(' ')].join(' ').toLowerCase().includes(term)).sort((a,b)=>asc?a.screenName.localeCompare(b.screenName):b.screenName.localeCompare(a.screenName));q('#reportCount').textContent=`${list.length} ${list.length===1?'item':'itens'}`;if(!selected)selected=list[0]?.id;q('#reportList').innerHTML=list.map(r=>`<button class="report-item ${r.id===selected?'active':''}" data-r="${r.id}"><span class="report-badge">${esc(r.screenName.replace(/APP\s*-\s*/i,'').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase())}</span><span class="report-copy"><strong>${esc(r.screenName)}</strong><small>${esc(r.formName||'Sem form')}</small></span><span class="star ${r.favorite?'on':''}" data-star="${r.id}">★</span></button>`).join('');renderDetail();renderFav()}
function renderDetail(){let r=reports.find(x=>x.id===selected),p=q('#reportDetail');if(!r){p.innerHTML='<div class="empty-state"><h2>Nenhum relatório</h2></div>';return}p.innerHTML=`<div class="detail-header"><div><span class="muted-label">${esc(r.category||'RELATÓRIOS / TELAS')}</span><h2>${esc(r.screenName)}</h2><p>Arquivo, print e informações da tela.</p></div><div class="detail-actions"><button class="secondary edit-report-btn" id="editReport">✎ ALTERAR</button><button class="secondary" id="favDetail">${r.favorite?'★ Favorito':'☆ Favoritar'}</button>${r.fr3Data?'<button class="secondary" id="downloadFr3">Baixar .FR3</button>':r.fr3Url?`<a class="secondary" href="${r.fr3Url}" download style="text-decoration:none">Baixar .FR3</a>`:''}${r.builtIn?'':'<button class="secondary danger" id="deleteReport">Excluir</button>'}</div></div><div class="meta-grid"><div class="meta-card"><span>Nome do Form</span><strong>${esc(r.formName||'Não informado')}</strong></div><div class="meta-card"><span>Arquivo FR3</span><strong>${esc(r.fr3Name||'Não anexado')}</strong></div><div class="meta-card"><span>Categoria</span><strong>${esc(r.category||'Relatórios / Telas')}</strong></div></div><div class="preview-wrap">${r.imageData?`<img src="${r.imageData}">`:'<div class="no-preview"><div class="symbol">▧</div><strong>Sem print cadastrado</strong><p>Clique em ALTERAR para inserir uma imagem.</p></div>'}</div>${r.notes?`<div class="notes-box"><span class="muted-label">OBSERVAÇÕES</span><p>${esc(r.notes)}</p></div>`:''}`}
function openReport(r){q('#reportForm').reset();q('#editingReportId').value=r?.id||'';q('#reportModalTitle').textContent=r?'Alterar relatório / tela':'Novo relatório / tela';q('#screenName').value=r?.screenName||'';q('#formName').value=r?.formName||'';q('#category').value=r?.category||'Relatórios / Telas';q('#tags').value=(r?.tags||[]).join(', ');q('#notes').value=r?.notes||'';q('#fr3Hint').textContent=r?.fr3Name?`Atual: ${r.fr3Name}`:'Selecione o relatório original';q('#imageHint').textContent=r?.imageData?'Imagem cadastrada; escolha outra para substituir':'PNG, JPG ou WEBP';q('#reportModal').showModal()}
function renderFav(){let a=reports.filter(x=>x.favorite);q('#favoritesList').innerHTML=a.length?a.map(r=>`<button class="favorite-card" data-fav="${r.id}"><strong>${esc(r.screenName)}</strong><br><small>${esc(r.formName||'')}</small></button>`).join(''):'<p>Nenhum favorito ainda.</p>'}
function fillClients(){let opts=CLIENTS.map(c=>`<option value="${esc(c.codigo)}">${esc(c.fantasia)} — ${esc(c.cidade)}/${esc(c.uf)}</option>`).join('');q('#hourClient').innerHTML='<option value="">Selecione...</option>'+opts;q('#clientFilter').innerHTML='<option value="">Todos</option>'+opts;let cities=[...new Set(CLIENTS.map(c=>`${c.cidade}/${c.uf}`).filter(x=>x!='/'))].sort();q('#cityFilter').innerHTML='<option value="">Todas</option>'+cities.map(x=>`<option>${esc(x)}</option>`).join('');let ufs=[...new Set(CLIENTS.map(c=>c.uf).filter(Boolean))].sort();q('#ufClientFilter').innerHTML='<option value="">Todas</option>'+ufs.map(x=>`<option>${x}</option>`).join('');updateClientCities()}
function filtered(){let p=q('#periodFilter').value,m=q('#monthFilter').value,cl=q('#clientFilter').value,ci=q('#cityFilter').value,tr=q('#travelFilter').checked,now=new Date(),yr=String(now.getFullYear()),mo=`${yr}-${String(now.getMonth()+1).padStart(2,'0')}`;return hours.filter(e=>{let c=byCode(e.clientCode)||{},k=`${c.cidade||e.city||''}/${c.uf||e.uf||''}`;return !(p==='month'&&!e.date.startsWith(m||mo))&&!(p==='year'&&!e.date.startsWith(yr))&&(!cl||String(e.clientCode)===cl)&&(!ci||k===ci)&&(!tr||e.travel)}).sort((a,b)=>b.date.localeCompare(a.date))}
function renderHours(){let a=filtered(),sum=a.reduce((s,e)=>s+total(e),0),hs=a.reduce((s,e)=>s+Number(e.hours||0),0);q('#sumBilling').textContent=brl(sum);q('#sumHours').textContent=fh(hs);q('#sumDays').textContent=new Set(a.map(e=>e.date)).size;q('#sumCities').textContent=new Set(a.map(e=>{let c=byCode(e.clientCode)||{};return`${c.cidade||e.city}/${c.uf||e.uf}`})).size;q('#hoursCount').textContent=`${a.length} registros`;q('#hoursTableBody').innerHTML=a.length?a.map(e=>{let c=byCode(e.clientCode)||{fantasia:e.clientName,cidade:e.city,uf:e.uf};return`<tr><td>${dateBR(e.date)}</td><td><strong>${esc(c.fantasia)}</strong></td><td>${esc(c.cidade)}/${esc(c.uf)}</td><td>${fh(e.hours)}</td><td>${brl(e.hourRate)}</td><td><span class="pill ${e.travel?'travel':''}">${e.travel?'SIM':'NÃO'}</span></td><td>${e.travel?brl(e.travelRate):'—'}</td><td class="money">${brl(total(e))}</td><td><div class="row-actions"><button class="mini-btn" data-eh="${e.id}">Alterar</button><button class="mini-btn" data-dh="${e.id}">Excluir</button></div></td></tr>`}).join(''):'<tr><td colspan="9" class="empty-state">Nenhum lançamento.</td></tr>';let g={};a.forEach(e=>{let c=byCode(e.clientCode)||{},k=`${c.cidade||e.city}/${c.uf||e.uf}`;g[k]??={h:0,t:0,n:0};g[k].h+=Number(e.hours);g[k].t+=total(e);g[k].n++});q('#citySummaryBody').innerHTML=Object.entries(g).sort((a,b)=>b[1].t-a[1].t).map(([k,v])=>`<tr><td><strong>${esc(k)}</strong></td><td>${fh(v.h)}</td><td class="money">${brl(v.t)}</td><td>${v.n}</td></tr>`).join('')||'<tr><td colspan="4" class="empty-state">Sem dados.</td></tr>'}
async function openHour(e){q('#hourForm').reset();q('#editingHourId').value=e?.id||'';q('#hourModalTitle').textContent=e?'Alterar lançamento':'Lançar horas';q('#hourDate').value=e?.date||new Date().toISOString().slice(0,10);q('#hourClient').value=e?.clientCode||'';q('#hourQty').value=e?.hours||'';q('#hourRate').value=e?.hourRate??await getSet('hourlyRate','');q('#travelRate').value=e?.travelRate??await getSet('travelRate','');q('#isTravel').checked=!!e?.travel;q('#hourNotes').value=e?.notes||'';calcPreview();q('#hourModal').showModal()}
function calcPreview(){q('#travelLabel').textContent=q('#isTravel').checked?'Sim':'Não';q('#hourCalcPreview').textContent=`Total do lançamento: ${brl(Number(q('#hourQty').value||0)*(Number(q('#hourRate').value||0)+(q('#isTravel').checked?Number(q('#travelRate').value||0):0)))}`}
function updateClientCities(){let uf=q('#ufClientFilter').value,a=[...new Set(CLIENTS.filter(c=>!uf||c.uf===uf).map(c=>c.cidade).filter(Boolean))].sort();q('#cityClientFilter').innerHTML='<option value="">Todas</option>'+a.map(x=>`<option>${esc(x)}</option>`).join('')}
function renderClients(){let t=q('#clientSearch').value.toLowerCase(),uf=q('#ufClientFilter').value,ci=q('#cityClientFilter').value,a=CLIENTS.filter(c=>(!t||[c.codigo,c.fantasia,c.nome,c.cidade,c.uf].join(' ').toLowerCase().includes(t))&&(!uf||c.uf===uf)&&(!ci||c.cidade===ci));q('#clientBaseInfo').textContent=`Base carregada com ${CLIENTS.length.toLocaleString('pt-BR')} clientes ativos.`;q('#clientCount').textContent=`${a.length.toLocaleString('pt-BR')} clientes`;q('#clientsTableBody').innerHTML=a.slice(0,500).map(c=>`<tr><td>${esc(c.codigo)}</td><td>${esc(c.fantasia)}</td><td>${esc(c.nome)}</td><td>${esc(c.cidade)}</td><td>${esc(c.uf)}</td></tr>`).join('')}
function nav(sec){qa('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.section===sec));qa('.section').forEach(x=>x.classList.add('hidden'));q(`#${sec}Section`).classList.remove('hidden');q('#pageTitle').textContent={reports:'Relatórios / Telas',hours:'Controle de Horas',clients:'Clientes Sisplan',favorites:'Favoritos',backup:'Backup'}[sec];q('#reportsTopActions').style.display=sec==='reports'?'flex':'none';if(sec==='hours')renderHours();if(sec==='clients')renderClients()}
document.addEventListener('click',async e=>{let n=e.target.closest('.nav-item');if(n)nav(n.dataset.section);let rb=e.target.closest('[data-r]');if(rb&&!e.target.closest('[data-star]')){selected=rb.dataset.r;renderReports()}let st=e.target.closest('[data-star]');if(st){let r=reports.find(x=>x.id===st.dataset.star);r.favorite=!r.favorite;await put(R,r);reports=await all(R);renderReports()}if(e.target.id==='newReportBtn')openReport();if(e.target.id==='editReport')openReport(reports.find(x=>x.id===selected));if(e.target.id==='favDetail'){let r=reports.find(x=>x.id===selected);r.favorite=!r.favorite;await put(R,r);reports=await all(R);renderReports()}if(e.target.id==='deleteReport'&&confirm('Excluir este relatório?')){await del(R,selected);reports=await all(R);selected=null;renderReports()}if(e.target.id==='downloadFr3'){let r=reports.find(x=>x.id===selected);if(r?.fr3Data)dl(r.fr3Data,r.fr3Name||'relatorio.fr3')}let f=e.target.closest('[data-fav]');if(f){selected=f.dataset.fav;nav('reports');renderReports()}if(e.target.id==='newHourBtn')openHour();let eh=e.target.closest('[data-eh]');if(eh)openHour(hours.find(x=>x.id===eh.dataset.eh));let dh=e.target.closest('[data-dh]');if(dh&&confirm('Excluir lançamento?')){await del(H,dh.dataset.dh);hours=await all(H);renderHours()}let c=e.target.closest('[data-close]');if(c)q('#'+c.dataset.close).close()});
q('#globalSearch').addEventListener('input',renderReports);q('#sortBtn').addEventListener('click',()=>{asc=!asc;renderReports()});
q('#reportForm').addEventListener('submit',async e=>{e.preventDefault();let id=q('#editingReportId').value,old=reports.find(x=>x.id===id)||{},fr=q('#fr3File').files[0],im=q('#imageFile').files[0],r={...old,id:id||'r-'+Date.now(),screenName:q('#screenName').value.trim(),formName:q('#formName').value.trim(),category:q('#category').value.trim()||'Relatórios / Telas',tags:q('#tags').value.split(',').map(x=>x.trim()).filter(Boolean),notes:q('#notes').value.trim(),favorite:old.favorite||false,createdAt:old.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),fr3Name:fr?.name||old.fr3Name||null,fr3Data:fr?await toText(fr):old.fr3Data||null,fr3Url:fr?null:old.fr3Url||null,imageData:im?await toData(im):old.imageData||null};await put(R,r);reports=await all(R);selected=r.id;q('#reportModal').close();renderReports()});
q('#saveRatesBtn').addEventListener('click',async()=>{await setSet('hourlyRate',q('#defaultHourlyRate').value);await setSet('travelRate',q('#defaultTravelRate').value);alert('Valores padrão salvos.')});['hourQty','hourRate','travelRate'].forEach(id=>q('#'+id).addEventListener('input',calcPreview));q('#isTravel').addEventListener('change',calcPreview);
q('#hourForm').addEventListener('submit',async e=>{e.preventDefault();let code=q('#hourClient').value,c=byCode(code)||{},o={id:q('#editingHourId').value||'h-'+Date.now(),date:q('#hourDate').value,clientCode:code,clientName:c.fantasia||'',city:c.cidade||'',uf:c.uf||'',hours:Number(q('#hourQty').value),hourRate:Number(q('#hourRate').value),travel:q('#isTravel').checked,travelRate:Number(q('#travelRate').value||0),notes:q('#hourNotes').value.trim(),updatedAt:new Date().toISOString()};await put(H,o);hours=await all(H);q('#hourModal').close();renderHours()});['periodFilter','monthFilter','clientFilter','cityFilter','travelFilter'].forEach(id=>q('#'+id).addEventListener('change',renderHours));
q('#ufClientFilter').addEventListener('change',()=>{updateClientCities();renderClients()});q('#cityClientFilter').addEventListener('change',renderClients);q('#clientSearch').addEventListener('input',renderClients);
q('#exportBtn').addEventListener('click',async()=>dl(JSON.stringify({app:'Controles Sisplan',version:2,reports:await all(R),hours:await all(H),settings:{hourlyRate:await getSet('hourlyRate',''),travelRate:await getSet('travelRate','')}},null,2),'controles-sisplan-backup.json','application/json'));
q('#importBackup').addEventListener('change',async e=>{try{let p=JSON.parse(await e.target.files[0].text());for(let r of p.reports||[])await put(R,r);for(let h of p.hours||[])await put(H,h);if(p.settings){await setSet('hourlyRate',p.settings.hourlyRate||'');await setSet('travelRate',p.settings.travelRate||'')}reports=await all(R);hours=await all(H);renderReports();renderHours();alert('Backup importado.')}catch{alert('Backup inválido.')}e.target.value=''});
(async()=>{await seed();reports=await all(R);hours=await all(H);selected=reports[0]?.id;fillClients();q('#defaultHourlyRate').value=await getSet('hourlyRate','');q('#defaultTravelRate').value=await getSet('travelRate','');let d=new Date();q('#monthFilter').value=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`;renderReports();renderHours();renderClients()})();